<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Laminas MVC Skeleton Application</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/laminas/laminas-mvc-skeleton" target="_blank">Laminas MVC Skeleton</a>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on Laminas MVC.
    </p>

    <p><a class="btn btn-success btn-lg" href="/application/index">Check Laminas on GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Create</h2>
            </div>
            <div class="card-body">
                <p>
                    Laminas Project is under active development. If you are
                    interested in following the development, you can check
                    <a href="https://getlaminas.org/blog/">Laminas dev blog</a>,
                    and <a href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:laminas">Laminas issue tracker</a>
                    (link requires a GitHub account). This is a great resource
                    for staying up to date with the latest developments!
                </p>

                <p><a class="btn btn-success pull-right" href="/application/create">Create &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Update</h2>
            </div>
            <div class="card-body">
                <p>
                    Laminas MVC is a modular application.
                    You can find multiple compatible modules on packagist.
                </p>

                <p><a class="btn btn-success pull-right" href="/application/update">Update &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Delete</h2>
            </div>
            <div class="card-body">
                <p>
                    If you need any help or support while developing with Laminas,
                    you may reach us via <a href="https://laminas.dev/chat">chat</a> or
                    <a href="https://discourse.laminas.dev">forum</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding any release.
                </p>

                <p><a class="btn btn-success pull-right" href="/application/delete">Delete &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
